mytuple = ('Sanjana','Shubham','Adnan','Suraj','Waseem','Mayur','Nikhil','Hasanmehmood')
print(mytuple)

print(mytuple[0:5])
print(mytuple[2:])
print(mytuple[:6])
print(mytuple[3:8])
print("______________")
print(mytuple[-5:-1])
print(mytuple[-1:-5])
print(mytuple[-8:-3])
print(mytuple[-2:-4])
print(mytuple[-2:4])
print(mytuple[-5:4])
print(mytuple[+6-4])
print("______________")

print(mytuple.count('Sanjana'))
print(mytuple.index('Hasanmehmood'))
mytuple.sort()
